// @generated by scripts/generate-contract.ts; do not edit.
const tokenNames = <const Names extends ReadonlyArray<string>>(names: Names): Names => names

export const RLY_COLOR_TOKEN_NAMES = tokenNames([
  "canvas",
  "surface-1",
  "surface-2",
  "surface-3",
  "text-1",
  "text-2",
  "text-3",
  "border-1",
  "border-2",
  "action-background",
  "action-foreground",
  "focus",
  "agent",
  "success-ink",
  "success-tint",
  "blocked-ink",
  "blocked-tint",
  "held-ink",
  "held-tint",
  "deploying-ink",
  "deploying-tint",
  "service-codecommit",
  "service-codepipeline",
  "service-jira",
  "service-confluence",
  "service-clockify"
])
export type RlyColorToken = (typeof RLY_COLOR_TOKEN_NAMES)[number]

export const RLY_SPACE_TOKEN_NAMES = tokenNames([
  "0",
  "2",
  "4",
  "6",
  "8",
  "12",
  "16",
  "20",
  "24",
  "32",
  "40",
  "48",
  "64",
  "80",
  "96"
])
export type RlySpaceToken = (typeof RLY_SPACE_TOKEN_NAMES)[number]

export const RLY_RADIUS_TOKEN_NAMES = tokenNames([
  "tag",
  "field",
  "control",
  "group",
  "overlay",
  "round"
])
export type RlyRadiusToken = (typeof RLY_RADIUS_TOKEN_NAMES)[number]

export const RLY_TYPE_TOKEN_NAMES = tokenNames([
  "verdict",
  "page-title",
  "section-title",
  "card-title",
  "body-large",
  "body",
  "label",
  "meta",
  "code"
])
export type RlyTypeToken = (typeof RLY_TYPE_TOKEN_NAMES)[number]

export const RLY_MOTION_TOKEN_NAMES = tokenNames([
  "instant",
  "fast",
  "standard",
  "deliberate"
])
export type RlyMotionToken = (typeof RLY_MOTION_TOKEN_NAMES)[number]
