# yaml-language-server: $schema=https://raw.githubusercontent.com/ast-grep/ast-grep/main/schemas/sgconfig.json

ruleDirs:
  - ast-grep/rules/effect
  - ast-grep/rules/typescript

languageGlobs:
  tsx:
    - "**/*.ts"
    - "**/*.tsx"
  javascript:
    - "**/*.mjs"

utilDirs: []
