import * as Data from "effect/Data"
import type { AssetEntry, ComponentManifest, ComponentRecord, EntryId, ModuleEntry } from "../component-manifest.js"
import { renderRegistryContract } from "./registry/registry-contract.js"
import { renderTokenContract } from "./tokens/token-contract.js"

const GENERATED_HEADER = "// @generated by scripts/generate-contract.ts; do not edit."

/** Raised when the checked-in component manifest violates the package contract. */
export class ContractError extends Data.TaggedError("ContractError")<{
  readonly reason: string
}> {
  override get message(): string {
    return this.reason
  }
}

const outputStem = (entry: ModuleEntry): string => (entry.subpath === "." ? "index" : `${entry.subpath.slice(2)}/index`)

const unique = (values: ReadonlyArray<string>, label: string): void => {
  const seen = new Set<string>()
  for (const value of values) {
    if (seen.has(value)) throw new ContractError({ reason: `Duplicate ${label}: ${value}` })
    seen.add(value)
  }
}

const validatePath = (value: string, label: string): void => {
  if (value.startsWith("/") || value.includes("\\") || value.split("/").includes("..")) {
    throw new ContractError({ reason: `Invalid ${label}: ${value}` })
  }
}

const validateAggregateCycles = (
  entry: ModuleEntry,
  entries: ReadonlyMap<EntryId, ModuleEntry>,
  ancestors: ReadonlySet<EntryId>
): void => {
  if (ancestors.has(entry.id)) throw new ContractError({ reason: `Aggregate cycle at ${entry.id}` })
  const nextAncestors = new Set(ancestors).add(entry.id)
  for (const aggregate of entry.aggregates) {
    const target = entries.get(aggregate)
    if (target === undefined) throw new ContractError({ reason: `Unknown aggregate entry: ${aggregate}` })
    if (entry.environment === "universal" && target.environment === "client") {
      throw new ContractError({ reason: `Universal entry ${entry.id} cannot aggregate client entry ${target.id}` })
    }
    validateAggregateCycles(target, entries, nextAncestors)
  }
}

/** Validate identity, path, aggregation, export, and variant invariants. */
export const validateManifest = (manifest: ComponentManifest): void => {
  unique(
    [...manifest.entries, ...manifest.assets].map(({ id }) => id),
    "entry id"
  )
  unique(
    [...manifest.entries, ...manifest.assets].map(({ subpath }) => subpath),
    "entry subpath"
  )
  unique(
    manifest.assets.map(({ output }) => output),
    "asset output"
  )
  unique(
    manifest.components.map(({ name }) => name),
    "component name"
  )
  unique(
    manifest.components.map(({ source }) => source),
    "component source"
  )
  unique(
    manifest.components.flatMap(({ styles }) => styles),
    "component style"
  )
  unique(
    manifest.components.flatMap((component) => component.exports.map(({ name }) => `${component.publicEntry}:${name}`)),
    "public export"
  )

  const registryComponents = manifest.components.filter(({ registry }) => registry)
  const registryNames = registryComponents.map(({ name }) => name).sort((left, right) => left.localeCompare(right))
  const metadataNames = Object.keys(manifest.registryMetadata).sort((left, right) => left.localeCompare(right))
  if (JSON.stringify(registryNames) !== JSON.stringify(metadataNames)) {
    throw new ContractError({ reason: "Registry metadata keys must exactly match registry component names" })
  }
  for (const component of registryComponents) {
    const metadata = manifest.registryMetadata[component.name]
    if (metadata === undefined) throw new ContractError({ reason: `Missing registry metadata for ${component.name}` })
    if (metadata.purpose.trim().length === 0) {
      throw new ContractError({ reason: `Missing registry purpose for ${component.name}` })
    }
    if (metadata.accessibility.length === 0 || metadata.accessibility.some((value) => value.trim().length === 0)) {
      throw new ContractError({ reason: `Missing accessibility metadata for ${component.name}` })
    }
    if (metadata.capabilities.length === 0 || metadata.capabilities.some((value) => value.trim().length === 0)) {
      throw new ContractError({ reason: `Missing capability metadata for ${component.name}` })
    }
    if (metadata.states.length === 0 || metadata.states.some((value) => value.trim().length === 0)) {
      throw new ContractError({ reason: `Missing state metadata for ${component.name}` })
    }
    unique(metadata.accessibility, `accessibility requirement in ${component.name}`)
    unique(metadata.capabilities, `capability in ${component.name}`)
    unique(metadata.states, `state in ${component.name}`)
  }

  const entries = new Map(manifest.entries.map((entry) => [entry.id, entry]))
  for (const entry of manifest.entries) {
    validatePath(entry.source, "entry source")
    validateAggregateCycles(entry, entries, new Set())
  }

  for (const asset of manifest.assets) {
    validatePath(asset.source, "asset source")
    validatePath(asset.output, "asset output")
  }

  for (const component of manifest.components) {
    validatePath(component.source, "component source")
    for (const style of component.styles) validatePath(style, "component style")
    validatePath(component.visual.story, "component story")
    for (const test of component.visual.tests) validatePath(test, "component test")
    if (component.visual.storyId.length === 0) {
      throw new ContractError({ reason: `Missing story id for ${component.name}` })
    }
    const storyIds = [component.visual.storyId, ...(component.visual.coverageStoryIds ?? [])]
    if (storyIds.some((storyId) => storyId.length === 0)) {
      throw new ContractError({ reason: `Missing coverage story id for ${component.name}` })
    }
    unique(storyIds, `story id in ${component.name}`)
    if (!entries.has(component.publicEntry)) {
      throw new ContractError({ reason: `Unknown component entry: ${component.publicEntry}` })
    }
    unique(
      component.exports.map(({ name }) => name),
      `export in ${component.name}`
    )
    for (const variant of component.variants) {
      unique(variant.values, `variant value in ${component.name}.${variant.name}`)
      if (variant.defaultValue !== undefined && !variant.values.includes(variant.defaultValue)) {
        throw new ContractError({ reason: `Invalid default for ${component.name}.${variant.name}` })
      }
    }
  }
}

const sortedEntries = (manifest: ComponentManifest): ReadonlyArray<ModuleEntry> =>
  [...manifest.entries].sort((left, right) => left.subpath.localeCompare(right.subpath))

const sortedAssets = (manifest: ComponentManifest): ReadonlyArray<AssetEntry> =>
  [...manifest.assets].sort((left, right) => left.subpath.localeCompare(right.subpath))

/** Project the manifest-owned component styles in deterministic build order. */
export const componentStyleSources = (manifest: ComponentManifest): ReadonlyArray<`src/${string}.css`> => {
  validateManifest(manifest)
  return manifest.components.flatMap(({ styles }) => styles).sort((left, right) => left.localeCompare(right))
}

const relativeModulePath = (entry: ModuleEntry, component: ComponentRecord): string => {
  const from = entry.source.split("/").slice(0, -1)
  const to = component.source.replace(/\.tsx?$/, ".js").split("/")
  while (from[0] !== undefined && from[0] === to[0]) {
    from.shift()
    to.shift()
  }
  const relative = [...from.map(() => ".."), ...to].join("/")
  return relative.startsWith(".") ? relative : `./${relative}`
}

const renderNamedExport = (kind: "type" | "value", names: ReadonlyArray<string>, from: string): string => {
  const prefix = kind === "type" ? "export type" : "export"
  const compact = `${prefix} { ${names.join(", ")} } from "${from}"`
  return compact.length <= 120
    ? compact
    : `${prefix} {\n${names.map((name) => `  ${name}`).join(",\n")}\n} from "${from}"`
}

/** Render the canonical package export object. */
export type PackageExportTarget = { readonly import: string; readonly types: string } | string

export const renderPackageExports = (manifest: ComponentManifest): Readonly<Record<string, PackageExportTarget>> => {
  validateManifest(manifest)
  return Object.fromEntries([
    ...sortedEntries(manifest).map((entry): readonly [string, PackageExportTarget] => {
      const stem = outputStem(entry)
      return [entry.subpath, { types: `./dist/dts/${stem}.d.ts`, import: `./dist/${stem}.js` }]
    }),
    ...sortedAssets(manifest).map((asset): readonly [string, PackageExportTarget] => [
      asset.subpath,
      `./${asset.output}`
    ])
  ])
}

/** Render package.json with its public exports replaced by the generated contract. */
export const renderPackageJson = (
  manifest: ComponentManifest,
  packageJson: Readonly<Record<string, unknown>>
): string => `${JSON.stringify({ ...packageJson, exports: renderPackageExports(manifest) }, null, 2)}\n`

/** Render the visual classifier's exact component path catalog. */
export const renderVisualCatalog = (manifest: ComponentManifest): string => {
  validateManifest(manifest)
  const components = [...manifest.components]
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((component) => ({
      name: component.name,
      paths: {
        source: `packages/rly/${component.source}`,
        story: `packages/rly/${component.visual.story}`,
        styles: [...component.styles].sort().map((style) => `packages/rly/${style}`),
        tests: [...component.visual.tests].sort().map((test) => `packages/rly/${test}`)
      },
      storyId: component.visual.storyId,
      storyIds: [component.visual.storyId, ...(component.visual.coverageStoryIds ?? [])]
    }))
  return `${JSON.stringify({ schemaVersion: 1, components }, null, 2)}\n`
}

const renderBarrel = (
  entry: ModuleEntry,
  entries: ReadonlyMap<EntryId, ModuleEntry>,
  components: ReadonlyArray<ComponentRecord>
): string => {
  const directives = entry.environment === "client" ? `${GENERATED_HEADER}\n"use client"\n` : GENERATED_HEADER
  const aggregateExports = [...entry.aggregates].sort().map((aggregate) => {
    const target = entries.get(aggregate)
    if (target === undefined) throw new ContractError({ reason: `Unknown aggregate entry: ${aggregate}` })
    const from = entry.subpath === "." ? `./${target.id}/index.js` : `../${target.id}/index.js`
    return `export * from "${from}"`
  })
  const componentExports = components
    .filter(({ publicEntry }) => publicEntry === entry.id)
    .sort(
      (left, right) =>
        relativeModulePath(entry, left).localeCompare(relativeModulePath(entry, right)) ||
        left.name.localeCompare(right.name)
    )
    .flatMap((component) => {
      const from = relativeModulePath(entry, component)
      const exports = [...component.exports].sort((left, right) => left.name.localeCompare(right.name))
      const values = exports.filter(({ kind }) => kind === "value").map(({ name }) => name)
      const types = exports.filter(({ kind }) => kind === "type").map(({ name }) => name)
      return [
        ...(values.length === 0 ? [] : [renderNamedExport("value", values, from)]),
        ...(types.length === 0 ? [] : [renderNamedExport("type", types, from)])
      ]
    })
  const exports = [...aggregateExports, ...componentExports]
  return `${directives}\n${exports.length === 0 ? "export {}" : exports.join("\n")}\n`
}

/** Find missing manifest sources and undeclared React component sources. */
export const findSourceDrift = (
  manifest: ComponentManifest,
  files: ReadonlyArray<string>
): { readonly missing: ReadonlyArray<string>; readonly unexpected: ReadonlyArray<string> } => {
  validateManifest(manifest)
  const normalizedFiles = new Set(files)
  const expected = new Set<string>([
    ...manifest.entries.map(({ source }) => source),
    ...manifest.assets.map(({ source }) => source).filter((source) => source.startsWith("src/")),
    ...manifest.components.flatMap(({ source, styles }) => [source, ...styles])
  ])
  const componentDirectories = new Set(
    manifest.entries
      .filter(({ id }) => id !== "root" && id !== "tokens")
      .map(({ source }) => source.slice(0, source.lastIndexOf("/")))
  )
  const candidates = files.filter((file) => {
    if (!file.endsWith(".tsx") && !file.endsWith(".css")) return false
    return [...componentDirectories].some((directory) => file.startsWith(`${directory}/`))
  })
  return {
    missing: [...expected].filter((file) => !normalizedFiles.has(file)).sort(),
    unexpected: candidates.filter((file) => !expected.has(file)).sort()
  }
}

/** Render every generated file as deterministic UTF-8 text. */
export const renderContract = (manifest: ComponentManifest): ReadonlyMap<string, string> => {
  validateManifest(manifest)
  const entries = new Map(manifest.entries.map((entry) => [entry.id, entry]))
  const viteEntries = Object.fromEntries(sortedEntries(manifest).map((entry) => [entry.id, entry.source]))
  const files = new Map<string, string>([
    ["generated/package-exports.json", `${JSON.stringify(renderPackageExports(manifest), null, 2)}\n`],
    ["generated/package-assets.json", `${JSON.stringify(sortedAssets(manifest), null, 2)}\n`],
    ["generated/visual-catalog.json", renderVisualCatalog(manifest)],
    [
      "generated/vite-entries.ts",
      `${GENERATED_HEADER}\nexport const moduleEntrySources = ${JSON.stringify(viteEntries, null, 2)} as const\n`
    ]
  ])
  for (const entry of sortedEntries(manifest)) {
    files.set(entry.source, renderBarrel(entry, entries, manifest.components))
  }
  for (const [path, content] of renderTokenContract()) {
    if (files.has(path)) throw new ContractError({ reason: `Duplicate generated path: ${path}` })
    files.set(path, content)
  }
  for (const [path, content] of renderRegistryContract(manifest)) {
    if (files.has(path)) throw new ContractError({ reason: `Duplicate generated path: ${path}` })
    files.set(path, content)
  }
  return files
}

/** Resolve a manifest entry to its emitted JavaScript and declaration stems. */
export const entryOutputStem = outputStem
