import * as NodeRuntime from "@effect/platform-node/NodeRuntime"
import * as NodeServices from "@effect/platform-node/NodeServices"
import * as Console from "effect/Console"
import * as Data from "effect/Data"
import * as Effect from "effect/Effect"
import * as FileSystem from "effect/FileSystem"
import * as Path from "effect/Path"
import * as Schema from "effect/Schema"

class StorybookValidationError extends Data.TaggedError("StorybookValidationError")<{
  readonly reason: string
}> {}

const StorybookIndex = Schema.fromJsonString(Schema.Struct({
  entries: Schema.Record(
    Schema.String,
    Schema.Struct({
      id: Schema.String,
      type: Schema.Literals(["story", "docs"])
    })
  )
}))

const program = Effect.gen(function*() {
  const fs = yield* FileSystem.FileSystem
  const path = yield* Path.Path
  const packageRoot = path.dirname(path.dirname(yield* path.fromFileUrl(new URL(import.meta.url))))
  const output = path.join(packageRoot, "storybook-static")
  const failures: Array<string> = []

  for (const file of ["index.html", "iframe.html", "index.json"]) {
    if (!(yield* fs.exists(path.join(output, file)))) failures.push(`missing ${file}`)
  }
  if (failures.length > 0) {
    return yield* Effect.fail(new StorybookValidationError({ reason: failures.join(", ") }))
  }

  const indexSource = yield* fs.readFileString(path.join(output, "index.json"))
  const index = yield* Schema.decodeUnknownEffect(StorybookIndex)(indexSource).pipe(
    Effect.mapError(() => new StorybookValidationError({ reason: "index.json is malformed" }))
  )
  const expected = new Map([
    ["catalog-overview--default", "story"],
    ["catalog-overview--documentation", "docs"],
    ["foundations-tokens--overview", "story"],
    ["foundations-tokens--documentation", "docs"]
  ])
  for (const [id, type] of expected) {
    const entry = index.entries[id]
    if (entry === undefined || entry.id !== id || entry.type !== type) {
      failures.push(`missing ${type} entry ${id}`)
    }
  }
  if (failures.length > 0) {
    return yield* Effect.fail(new StorybookValidationError({ reason: failures.join(", ") }))
  }

  yield* Console.log("validated Storybook story and autogenerated documentation navigation")
})

NodeRuntime.runMain(
  program.pipe(
    Effect.tapError((error) => Console.error(error)),
    Effect.provide(NodeServices.layer)
  ),
  { disableErrorReporting: true }
)
