import type { ComponentManifest, ComponentRecord, RegistryMetadata } from "../../component-manifest.js"

const GENERATED_NOTICE = "Generated from @knpkv/rly/component-manifest.ts. Do not edit."

const publicImportPath = (component: ComponentRecord): string =>
  component.publicEntry === "root" ? "@knpkv/rly" : `@knpkv/rly/${component.publicEntry}`

const componentProps = (component: ComponentRecord): ReadonlyArray<string> =>
  component.exports
    .filter(({ kind, name }) => kind === "type" && name.endsWith("Props"))
    .map(({ name }) => name)
    .sort((left, right) => left.localeCompare(right))

const componentSlots = (component: ComponentRecord): ReadonlyArray<string> =>
  componentProps(component)
    .filter((name) => name !== `${component.name}Props`)
    .map((name) => name.replace(/Props$/, ""))

const variantDescription = (component: ComponentRecord, name: string): string =>
  `Controls the ${name} presentation axis of ${component.name}.`

const variantValueDescription = (variantName: string, value: string): string =>
  `Use ${value} for the ${variantName} presentation.`

const componentExample = (component: ComponentRecord): string => {
  const valueExport = component.exports.find(({ kind }) => kind === "value")
  if (valueExport === undefined) {
    return `import type { ${component.exports[0]?.name ?? component.name} } from "${publicImportPath(component)}"`
  }
  return `import { ${valueExport.name} } from "${publicImportPath(component)}"`
}

const registryComponent = (
  component: ComponentRecord,
  metadata: RegistryMetadata
): Readonly<Record<string, unknown>> => ({
  accessibility: {
    automatedChecks: true,
    requirements: [...metadata.accessibility],
    standard: "WCAG 2.2 AA"
  },
  capabilities: [...metadata.capabilities].sort((left, right) => left.localeCompare(right)),
  category: component.category,
  compatibleTokens: ["color", "motion", "radius", "space", "type"],
  docs: {
    autogenerated: true,
    storyId: component.visual.storyId,
    storyPath: `?path=/story/${component.visual.storyId}`
  },
  example: componentExample(component),
  exports: [...component.exports].sort((left, right) => left.name.localeCompare(right.name)),
  files: {
    source: component.source,
    story: component.visual.story,
    styles: [...component.styles].sort((left, right) => left.localeCompare(right)),
    tests: [...component.visual.tests].sort((left, right) => left.localeCompare(right))
  },
  importPath: publicImportPath(component),
  name: component.name,
  props: {
    defaults: Object.fromEntries(
      component.variants
        .filter(({ defaultValue }) => defaultValue !== undefined)
        .sort((left, right) => left.name.localeCompare(right.name))
        .map(({ defaultValue, name }) => [name, defaultValue])
    ),
    types: componentProps(component)
  },
  purpose: metadata.purpose,
  slots: componentSlots(component),
  states: [...new Set(["default", ...metadata.states, ...component.variants.flatMap(({ values }) => values)])].sort(
    (left, right) => left.localeCompare(right)
  ),
  status: component.status,
  variants: [...component.variants]
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((variant) => ({
      ...(variant.defaultValue === undefined ? {} : { defaultValue: variant.defaultValue }),
      description: variantDescription(component, variant.name),
      name: variant.name,
      values: [...variant.values]
        .sort((left, right) => left.localeCompare(right))
        .map((value) => ({
          description: variantValueDescription(variant.name, value),
          name: value
        }))
    }))
})

/** Render the complete deterministic agent-readable component registry. */
export const renderComponentsRegistry = (manifest: ComponentManifest): string => {
  const components = manifest.components
    .filter(({ registry }) => registry)
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((component) => {
      const metadata = manifest.registryMetadata[component.name]
      if (metadata === undefined) throw new Error(`Missing registry metadata for ${component.name}`)
      return registryComponent(component, metadata)
    })
  return `${
    JSON.stringify({ generatedNotice: GENERATED_NOTICE, package: "@knpkv/rly", schemaVersion: 1, components }, null, 2)
  }\n`
}

/** Render a small search index without component implementation or executable payloads. */
export const renderSearchRegistry = (manifest: ComponentManifest): string => {
  const records = manifest.components
    .filter(({ registry }) => registry)
    .sort((left, right) => left.name.localeCompare(right.name))
    .map((component) => {
      const metadata = manifest.registryMetadata[component.name]
      if (metadata === undefined) throw new Error(`Missing registry metadata for ${component.name}`)
      return {
        capabilities: [...metadata.capabilities].sort((left, right) => left.localeCompare(right)),
        category: component.category,
        importPath: publicImportPath(component),
        name: component.name,
        states: [...new Set(["default", ...metadata.states])].sort((left, right) => left.localeCompare(right)),
        terms: [
          ...new Set([
            component.name.toLocaleLowerCase("en-US"),
            component.category,
            ...metadata.capabilities,
            ...metadata.states,
            ...component.variants.flatMap(({ name, values }) => [name, ...values])
          ])
        ].sort((left, right) => left.localeCompare(right))
      }
    })
  return `${
    JSON.stringify({ generatedNotice: GENERATED_NOTICE, package: "@knpkv/rly", schemaVersion: 1, records }, null, 2)
  }\n`
}

/** Render the JSON Schema used by packed consumers to validate components.json. */
export const renderRegistrySchema = (): string =>
  `${
    JSON.stringify(
      {
        $schema: "https://json-schema.org/draft/2020-12/schema",
        $id: "https://knpkv.dev/schemas/rly/components.schema.json",
        additionalProperties: false,
        properties: {
          components: {
            items: {
              additionalProperties: false,
              properties: {
                accessibility: {
                  additionalProperties: false,
                  properties: {
                    automatedChecks: { const: true },
                    requirements: {
                      items: { minLength: 1, type: "string" },
                      minItems: 1,
                      type: "array",
                      uniqueItems: true
                    },
                    standard: { const: "WCAG 2.2 AA" }
                  },
                  required: ["automatedChecks", "requirements", "standard"],
                  type: "object"
                },
                capabilities: {
                  type: "array",
                  items: { type: "string", minLength: 1 },
                  minItems: 1,
                  uniqueItems: true
                },
                category: { enum: ["foundation", "primitive", "pattern", "diff"], type: "string" },
                compatibleTokens: { type: "array", items: { type: "string", minLength: 1 }, uniqueItems: true },
                docs: {
                  additionalProperties: false,
                  properties: {
                    autogenerated: { const: true },
                    storyId: { minLength: 1, pattern: "^[a-z0-9-]+--[a-z0-9-]+$", type: "string" },
                    storyPath: { minLength: 1, pattern: "^\\?path=/story/[a-z0-9-]+--[a-z0-9-]+$", type: "string" }
                  },
                  required: ["autogenerated", "storyId", "storyPath"],
                  type: "object"
                },
                example: { type: "string", minLength: 1 },
                exports: {
                  items: {
                    additionalProperties: false,
                    properties: {
                      kind: { enum: ["type", "value"], type: "string" },
                      name: { minLength: 1, type: "string" }
                    },
                    required: ["kind", "name"],
                    type: "object"
                  },
                  minItems: 1,
                  type: "array"
                },
                files: {
                  additionalProperties: false,
                  properties: {
                    source: { minLength: 1, pattern: "^src/", type: "string" },
                    story: { minLength: 1, pattern: "^stories/", type: "string" },
                    styles: {
                      items: { minLength: 1, pattern: "^src/", type: "string" },
                      type: "array",
                      uniqueItems: true
                    },
                    tests: {
                      items: { minLength: 1, pattern: "^test/", type: "string" },
                      minItems: 1,
                      type: "array",
                      uniqueItems: true
                    }
                  },
                  required: ["source", "story", "styles", "tests"],
                  type: "object"
                },
                importPath: {
                  type: "string",
                  pattern: "^@knpkv/rly(?:/(?:tokens|foundations|primitives|patterns|diff))?$"
                },
                name: { type: "string", minLength: 1 },
                props: {
                  additionalProperties: false,
                  properties: {
                    defaults: { additionalProperties: { minLength: 1, type: "string" }, type: "object" },
                    types: { items: { minLength: 1, type: "string" }, type: "array", uniqueItems: true }
                  },
                  required: ["defaults", "types"],
                  type: "object"
                },
                purpose: { type: "string", minLength: 1 },
                slots: { type: "array", items: { type: "string", minLength: 1 }, uniqueItems: true },
                states: { type: "array", items: { type: "string", minLength: 1 }, minItems: 1, uniqueItems: true },
                status: { enum: ["experimental", "stable", "deprecated"], type: "string" },
                variants: {
                  items: {
                    additionalProperties: false,
                    properties: {
                      defaultValue: { minLength: 1, type: "string" },
                      description: { minLength: 1, type: "string" },
                      name: { minLength: 1, type: "string" },
                      values: {
                        items: {
                          additionalProperties: false,
                          properties: {
                            description: { minLength: 1, type: "string" },
                            name: { minLength: 1, type: "string" }
                          },
                          required: ["description", "name"],
                          type: "object"
                        },
                        minItems: 1,
                        type: "array"
                      }
                    },
                    required: ["description", "name", "values"],
                    type: "object"
                  },
                  type: "array"
                }
              },
              required: [
                "accessibility",
                "capabilities",
                "category",
                "compatibleTokens",
                "docs",
                "example",
                "exports",
                "files",
                "importPath",
                "name",
                "props",
                "purpose",
                "slots",
                "states",
                "status",
                "variants"
              ],
              type: "object"
            },
            minItems: 1,
            type: "array"
          },
          generatedNotice: { type: "string", minLength: 1 },
          package: { const: "@knpkv/rly" },
          schemaVersion: { const: 1 }
        },
        required: ["components", "generatedNotice", "package", "schemaVersion"],
        title: "@knpkv/rly component registry",
        type: "object"
      },
      null,
      2
    )
  }\n`

/** Render non-executable usage guidance alongside the machine-readable registry. */
export const renderRegistryUsage = (): string =>
  `# rly agent registry

${GENERATED_NOTICE}

Use \`components.json\` to choose an existing typed rly export, then import that export from its declared \`importPath\`.
Use \`search.json\` for discovery and \`schema.json\` to validate \`components.json\` before indexing it.

Maintainers can create a complete component slice with:

\`pnpm --filter @knpkv/rly scaffold -- <foundation|primitive|pattern|diff> <PascalName> "<purpose>"\`

The scaffolder validates the name, intent, manifest markers, duplicate records, and every target path before writing. A successful run creates source, focused CSS, all-state Storybook story, DOM/a11y test, manifest metadata, generated registry, and public index together.

The registry is documentation and planning input. It contains no component implementation, expression, callback, or JSON-to-React execution format. Applications must continue to compile typed React presenters and govern actions outside rly.
`

/** Render all public registry artifacts. */
export const renderRegistryContract = (manifest: ComponentManifest): ReadonlyMap<string, string> =>
  new Map([
    ["registry/components.json", renderComponentsRegistry(manifest)],
    ["registry/schema.json", renderRegistrySchema()],
    ["registry/search.json", renderSearchRegistry(manifest)],
    ["registry/USAGE.md", renderRegistryUsage()]
  ])
