import { colorTokenSource, contrastPairSource } from "../../src/tokens/colors.js"
import { controlHeightTokenSource } from "../../src/tokens/control.js"
import { easingTokenSource, motionTokenSource } from "../../src/tokens/motion.js"
import { radiusTokenSource } from "../../src/tokens/shape.js"
import { spaceTokenSource } from "../../src/tokens/space.js"
import { typeTokenSource } from "../../src/tokens/typography.js"
import { measureContrastPairs } from "./contrast.js"

const TS_HEADER = "// @generated by scripts/generate-contract.ts; do not edit."
const CSS_HEADER = "/* @generated by scripts/generate-contract.ts; do not edit. */"

const uniqueNames = (
  values: ReadonlyArray<{ readonly name: string }>,
  group: string,
  pattern: RegExp = /^[a-z][a-z0-9-]*$/
): void => {
  const names = new Set<string>()
  for (const { name } of values) {
    if (!pattern.test(name)) throw new Error(`Invalid ${group} token name: ${name}`)
    if (names.has(name)) throw new Error(`Duplicate ${group} token name: ${name}`)
    names.add(name)
  }
}

/** Validate the private token source before emitting any public artifact. */
export const validateTokenSource = (): void => {
  uniqueNames(colorTokenSource, "color")
  uniqueNames(spaceTokenSource, "space", /^\d+$/)
  uniqueNames(radiusTokenSource, "radius")
  uniqueNames(typeTokenSource, "type")
  uniqueNames(motionTokenSource, "motion")
  uniqueNames(easingTokenSource, "easing")
  uniqueNames(controlHeightTokenSource, "control height")
  for (const result of measureContrastPairs(colorTokenSource, contrastPairSource)) {
    if (result.ratio < result.minimum) {
      throw new Error(
        `${result.name} ${result.scheme} contrast ${result.ratio.toFixed(2)} is below ${result.minimum}`
      )
    }
  }
}

const declaration = (name: string, value: string): string => `    --rly-${name}: ${value};`

const renderForcedColors = (): string =>
  colorTokenSource
    .map((token) => declaration(`color-${token.name}`, token.forced))
    .join("\n")

const renderReducedMotion = (): string =>
  motionTokenSource
    .map((token) => declaration(`motion-${token.name}-duration`, token.reducedDuration))
    .join("\n")

const renderCoarseControlHeights = (): string =>
  controlHeightTokenSource
    .map((token) => declaration(`control-height-${token.name}`, token.coarse))
    .join("\n")

const renderSchemeColors = (): string =>
  colorTokenSource
    .map((token) => declaration(`color-${token.name}`, `light-dark(${token.light}, ${token.dark})`))
    .join("\n")

/**
 * Render the complete central token/theme layer. Colours are declared once, on :root, as light-dark(): an
 * unregistered custom property resolves light-dark() where it is used, so a [data-theme] subtree only
 * sets color-scheme and its descendants pick the matching value without the tokens being re-declared.
 */
export const renderTokenCss = (): string => {
  validateTokenSource()
  const root = [
    declaration("font-ui", "\"Geist Variable\", \"Geist\", \"Geist Fallback\", system-ui, sans-serif"),
    declaration(
      "font-mono",
      "\"Geist Mono Variable\", \"Geist Mono\", \"Geist Mono Fallback\", ui-monospace, monospace"
    ),
    // One solid, high-contrast focus ring: 2px, drawn 2px outside the control (inset rings negate the width).
    declaration("focus-ring-width", "2px"),
    declaration("focus-ring-offset", "2px"),
    renderSchemeColors(),
    ...spaceTokenSource.map((token) => declaration(`space-${token.name}`, token.value)),
    ...radiusTokenSource.map((token) => declaration(`radius-${token.name}`, token.value)),
    ...controlHeightTokenSource.map((token) => declaration(`control-height-${token.name}`, token.value)),
    ...typeTokenSource.flatMap((token) => [
      declaration(`type-${token.name}-font`, `var(--rly-font-${token.font})`),
      declaration(`type-${token.name}-size`, token.size),
      declaration(`type-${token.name}-line-height`, token.lineHeight),
      declaration(`type-${token.name}-weight`, String(token.weight)),
      declaration(`type-${token.name}-tracking`, token.tracking)
    ]),
    ...motionTokenSource.flatMap((token) => [
      declaration(`motion-${token.name}-duration`, token.duration),
      declaration(`motion-${token.name}-easing`, token.easing)
    ]),
    ...easingTokenSource.map((token) => declaration(`easing-${token.name}`, token.value))
  ].join("\n")

  return `${CSS_HEADER}
@layer rly.tokens {
  :root {
    color-scheme: light dark;
${root}
  }

  :root:is([data-theme="light"], [data-rly-theme="light"]),
  :where([data-theme="light"], [data-rly-theme="light"]) { color-scheme: light; }
  :root:is([data-theme="dark"], [data-rly-theme="dark"]),
  :where([data-theme="dark"], [data-rly-theme="dark"]) { color-scheme: dark; }
  :root:is([data-theme="system"], [data-rly-theme="system"]),
  :where([data-theme="system"], [data-rly-theme="system"]) { color-scheme: light dark; }

  @media (forced-colors: active) {
    :root {
${renderForcedColors()}
    }
  }

  :root:is([data-forced-colors="active"], [data-rly-forced-colors="active"]),
  :where([data-forced-colors="active"], [data-rly-forced-colors="active"]) {
${renderForcedColors()}
  }

  @media (prefers-reduced-motion: reduce) {
    :root {
${renderReducedMotion()}
    }
  }

  @media (pointer: coarse) {
    :root {
${renderCoarseControlHeights()}
    }
  }

  :root:is([data-reduced-motion="reduce"], [data-rly-reduced-motion="reduce"]),
  :where([data-reduced-motion="reduce"], [data-rly-reduced-motion="reduce"]) {
${renderReducedMotion()}
  }
}
`
}

const renderNames = (constant: string, type: string, names: ReadonlyArray<string>): string =>
  `export const ${constant} = tokenNames([\n${
    names.map((name) => `  ${JSON.stringify(name)}`).join(",\n")
  }\n])\nexport type ${type} = (typeof ${constant})[number]\n`

/** Render browser-safe public token names without exposing the private palette. */
export const renderTokenTypescript = (): string => {
  validateTokenSource()
  return `${TS_HEADER}
const tokenNames = <const Names extends ReadonlyArray<string>>(names: Names): Names => names

${renderNames("RLY_COLOR_TOKEN_NAMES", "RlyColorToken", colorTokenSource.map(({ name }) => name))}
${renderNames("RLY_SPACE_TOKEN_NAMES", "RlySpaceToken", spaceTokenSource.map(({ name }) => name))}
${renderNames("RLY_RADIUS_TOKEN_NAMES", "RlyRadiusToken", radiusTokenSource.map(({ name }) => name))}
${renderNames("RLY_TYPE_TOKEN_NAMES", "RlyTypeToken", typeTokenSource.map(({ name }) => name))}
${renderNames("RLY_MOTION_TOKEN_NAMES", "RlyMotionToken", motionTokenSource.map(({ name }) => name))}
${renderNames("RLY_EASING_TOKEN_NAMES", "RlyEasingToken", easingTokenSource.map(({ name }) => name))}
${
    renderNames(
      "RLY_CONTROL_HEIGHT_TOKEN_NAMES",
      "RlyControlHeightToken",
      controlHeightTokenSource.map(({ name }) => name)
    )
  }`
}

/** Render registry metadata for tooling and later docs generation. */
export const renderTokenRegistry = (): string => {
  validateTokenSource()
  return `${
    JSON.stringify(
      {
        schemaVersion: 1,
        color: colorTokenSource,
        controlHeight: controlHeightTokenSource,
        contrast: measureContrastPairs(colorTokenSource, contrastPairSource).map((result) => ({
          ...result,
          ratio: Number(result.ratio.toFixed(2))
        })),
        easing: easingTokenSource,
        motion: motionTokenSource,
        radius: radiusTokenSource,
        space: spaceTokenSource,
        typography: typeTokenSource
      },
      null,
      2
    )
  }\n`
}

export const renderTokenContract = (): ReadonlyMap<string, string> =>
  new Map([
    ["generated/tokens.json", renderTokenRegistry()],
    ["src/styles/generated-tokens.css", renderTokenCss()],
    ["src/tokens/semantic-tokens.ts", renderTokenTypescript()]
  ])
